### ISSUE TITLE
Dropping m12 format file does not respond.

### ISSUE THREAD

**Issue by ShiN-K-278** [takamin/mz700-js#189] opened 2020-06-07 10:14 UTC
In v1.4.0, dropping m12 format file does not respond.

**Comment by takamin** [comment] 2020-09-13 01:08
@ShiN-K-278 Sorry, I didn't notice this issue was opened bacause of my job was so so busy in this summer.

I don't know details of the m12 format.

Is it same to `MZT` that has 128 bytes header including the filename, binary size, loading and excution addresses?

**Comment by ShiN-K-278** [comment] 2020-09-18 08:34
I don't know the details inside the m12 file.
Examples of m12 files are below.

http://mzakd.cool.coocan.jp/mz-memories/mz700win.html

eugea.lzh
furu1.lzh

**Comment by takamin** [comment] 2020-09-20 00:59
@ShiN-K-278 Thanks the samples for m12 file.

I found that the `.m12` format is same to `.mzt`.
It is described on [KM-Z80 game ver 0.9](https://www.recfor.net/blog/mycom/index.php?itemid=931).

Therefore, I would fix this problem that the emulater could not accept `.m12` file.

Until the fixed version is released, rename the extension to 'mzt', and you can drop the file to run.

**Comment by takamin** [comment] 2020-09-20 08:00
Now, [mz700-js@1.4.4](https://takamin.github.io/mz700-js/emu) can accept `.m12` file.

Please close this issue, if you confirm that the problem is fixed.

**Comment by ShiN-K-278** [comment] 2020-09-20 09:23
I have confirmed that the m12 file I have works. Thank you very much.

**Closed** 2020-09-20 09:23 UTC
